version: 1.0.{build}
configuration: Release
before_build:
  - nuget restore dapper-studies.sln
build:
  project: dapper-studies.sln
  verbosity: minimal
  publish_nuget: false
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
branches:
  only:
    - master
